(() => {
  const VERSION = '26.0';
  const SUBJECTS = {
    math:{label:'Matemáticas',icon:'➗',action:'Mueve, agrupa y descubre la operación.',scene:'Mira la idea matemática en movimiento.'},
    language:{label:'Lenguaje',icon:'📖',action:'Toca las palabras y observa la historia.',scene:'Las palabras cobran vida para mostrar su función.'},
    science:{label:'Ciencias',icon:'🔬',action:'Activa cada etapa y observa qué cambia.',scene:'Explora el proceso antes de explicarlo.'},
    social:{label:'Sociales',icon:'🌎',action:'Recorre los puntos de la historia.',scene:'Viaja por la situación antes de responder.'},
    english:{label:'Inglés',icon:'💬',action:'Toca objetos y palabras para asociarlos.',scene:'Aprende la palabra dentro de una escena.'}
  };
  let gameSignature='',topicSignature='',atlasSignature='',academySignature='',notebookSignature='';
  const q=(s,r=document)=>r?.querySelector?.(s)||null;
  const qa=(s,r=document)=>[...(r?.querySelectorAll?.(s)||[])];
  const text=(s,r=document)=>String(q(s,r)?.textContent||'').replace(/\s+/g,' ').trim();
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const short=(v,n=100)=>{const s=String(v||'').replace(/\s+/g,' ').trim();return s.length>n?`${s.slice(0,n-1).trim()}…`:s};
  const visible=el=>Boolean(el&&!el.hidden&&el.getClientRects().length);
  const track=(event,properties={})=>window.NOVAAnalytics?.track?.(event,properties,'app');

  function subjectFrom(value=''){
    const s=String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
    if(/lenguaje|lectura|escrit|oracion|palabra|verbo|sustant/.test(s))return'language';
    if(/ciencia|animal|planta|agua|materia|energia|cuerpo|ecosistema/.test(s))return'science';
    if(/social|historia|geograf|comunidad|colombia|mapa|territorio/.test(s))return'social';
    if(/ingles|english|vocab|word|sentence/.test(s))return'english';
    return'math';
  }
  function activeSubject(root=document){return subjectFrom([
    text('#curriculumGameKicker',root),text('#curriculumTopicKicker',root),text('#curriculumSubjectKicker',root),
    text('#curriculumGameTitle',root),text('#curriculumTopicTitle',root),text('#curriculumSubjectTitle',root)
  ].join(' '));}
  function shell({subject,title,copy,compact=false}){
    const cfg=SUBJECTS[subject]||SUBJECTS.math;
    return `<section class="v26-scene v26-${subject}${compact?' v26-scene-compact':''}" data-v26-scene="${subject}">
      <div class="v26-scene-copy"><span>${cfg.icon} MIRA · TOCA · DESCUBRE</span><strong>${esc(short(title||cfg.scene,72))}</strong>${copy?`<p>${esc(short(copy,112))}</p>`:''}</div>
      <div class="v26-stage"></div><button type="button" class="v26-scene-action">${esc(cfg.action)}</button></section>`;
  }
  function celebrate(root){for(let i=0;i<8;i++){const s=document.createElement('span');s.className='v26-spark';s.textContent=i%2?'✦':'⭐';s.style.setProperty('--x',`${-80+Math.random()*160}px`);s.style.left=`${38+Math.random()*24}%`;s.style.top=`${42+Math.random()*20}%`;root.appendChild(s);setTimeout(()=>s.remove(),1200)}}

  function mathStage(stage,prompt){
    const raw=String(prompt||''),norm=raw.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
    const nums=(raw.match(/\d+/g)||[]).map(Number).filter(Number.isFinite),a=Math.max(1,Math.min(10,nums[0]||6)),b=Math.max(1,Math.min(6,nums[1]||3));
    const add=/\+|sum|adicion|agreg|junt/.test(norm),sub=/-|rest|quit|diferencia|falt/.test(norm),mul=/×|x|multiplic|veces|grupos de/.test(norm),div=/÷|\/|divi|repart|partes iguales|cuantas veces cabe/.test(norm)||(!add&&!sub&&!mul&&nums.length>=2);
    if(add){const l=Math.min(a,8),r=Math.min(b,8);stage.innerHTML=`<div class="v26-character">🐼 <small>Juntemos</small></div><div class="v26-add zone-a">${Array.from({length:l},()=>'<button>⭐</button>').join('')}</div><b class="v26-op">＋</b><div class="v26-add zone-b">${Array.from({length:r},()=>'<button>⭐</button>').join('')}</div><div class="v26-caption">Toca las estrellas para juntarlas.</div>`;let n=0;qa('.v26-add button',stage).forEach(btn=>btn.onclick=()=>{if(btn.dataset.on)return;btn.dataset.on='1';btn.classList.add('on');if(++n===l+r){q('.v26-caption',stage).textContent=`${l} + ${r} = ${l+r}. Juntamos dos cantidades.`;celebrate(stage)}});return}
    if(sub){const shown=Math.min(a,10),remove=Math.min(b,Math.max(1,shown-1));stage.innerHTML=`<div class="v26-character">🐼 <small>¿Qué queda?</small></div><div class="v26-sub">${Array.from({length:shown},()=>'<button>🍎</button>').join('')}</div><div class="v26-caption">Quita ${remove} objetos tocándolos.</div>`;let n=0;qa('.v26-sub button',stage).forEach(btn=>btn.onclick=()=>{if(btn.dataset.off||n>=remove)return;btn.dataset.off='1';btn.classList.add('off');n++;q('.v26-caption',stage).textContent=n===remove?`${shown} − ${remove} = ${shown-remove}. Lo que queda es la diferencia.`:`Has quitado ${n} de ${remove}.`;if(n===remove)celebrate(stage)});return}
    if(mul){const groups=Math.min(a,4),each=Math.min(b,5);stage.innerHTML=`<div class="v26-character">🐼 <small>Grupos iguales</small></div><div class="v26-mul">${Array.from({length:groups},(_,g)=>`<button><span>${Array.from({length:each},()=> '●').join(' ')}</span><b>grupo ${g+1}</b></button>`).join('')}</div><div class="v26-caption">Toca los grupos para contarlos.</div>`;qa('.v26-mul button',stage).forEach(btn=>btn.onclick=()=>{btn.classList.toggle('on');const n=qa('.v26-mul button.on',stage).length;q('.v26-caption',stage).textContent=n===groups?`${groups} grupos de ${each} = ${groups*each}. Eso es multiplicar.`:`Has contado ${n} de ${groups} grupos.`;if(n===groups)celebrate(stage)});return}
    if(div){const total=Math.max(6,Math.min(12,a)),groups=Math.max(2,Math.min(4,b));stage.innerHTML=`<div class="v26-character">🐼 <small>¿Repartimos?</small></div><div class="v26-bank">${Array.from({length:total},()=>'<button>🍓</button>').join('')}</div><div class="v26-groups">${Array.from({length:groups},(_,i)=>`<div><span>${['🐰','🦊','🐸','🐧'][i]}</span><b>0</b></div>`).join('')}</div><div class="v26-caption">Toca las fresas para repartirlas.</div>`;let n=0;qa('.v26-bank button',stage).forEach(btn=>btn.onclick=()=>{if(btn.dataset.on)return;btn.dataset.on='1';btn.classList.add('on');const target=qa('.v26-groups div',stage)[n%groups],count=q('b',target);count.textContent=String(Number(count.textContent)+1);target.classList.add('pop');setTimeout(()=>target.classList.remove('pop'),300);n++;if(n===total){q('.v26-caption',stage).textContent=`${total} repartido entre ${groups}: ${Math.floor(total/groups)} en cada grupo.`;celebrate(stage)}});return}
    stage.innerHTML=`<div class="v26-numberline">${Array.from({length:11},(_,i)=>`<button>${i}</button>`).join('')}</div><div class="v26-caption">Toca un número y observa su posición.</div>`;qa('.v26-numberline button',stage).forEach(btn=>btn.onclick=()=>{qa('.v26-numberline button',stage).forEach(x=>x.classList.remove('on'));btn.classList.add('on')});
  }
  function languageStage(stage,prompt){let words=String(prompt).replace(/[¿?¡!.,:;]/g,'').split(/\s+/).filter(Boolean).slice(0,8);if(words.length<4)words=['El','zorro','corre','rápido'];stage.innerHTML=`<div class="v26-character">🦊 <small>Haz vivir la oración</small></div><div class="v26-words">${words.map(w=>`<button>${esc(w)}</button>`).join('')}</div><div class="v26-action">💨</div><div class="v26-caption">Toca una palabra para verla entrar en escena.</div>`;qa('.v26-words button',stage).forEach((btn,i)=>btn.onclick=()=>{qa('.v26-words button',stage).forEach(x=>x.classList.remove('on'));btn.classList.add('on');q('.v26-action',stage).style.transform=`translate(${(i%4-1.5)*34}px,${i%2?-8:12}px) rotate(${i%2?8:-8}deg)`;q('.v26-caption',stage).textContent=`“${btn.textContent}” ahora es la pista principal.`})}
  function scienceStage(stage,prompt){const n=String(prompt).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();let phases=/agua|lluv|evapor|nube|ciclo/.test(n)?[['☀️','Calor'],['💧','Agua'],['☁️','Nube'],['🌧️','Lluvia']]:/planta|hoja|raiz|fotosint/.test(n)?[['🌱','Raíz'],['💧','Agua'],['☀️','Luz'],['🌿','Crecimiento']]:/animal|habitat|ecosistema/.test(n)?[['🌿','Hábitat'],['🐾','Animal'],['🍎','Alimento'],['♻️','Relación']]:[['👀','Observar'],['🔬','Examinar'],['🧪','Probar'],['💡','Concluir']];stage.innerHTML=`<div class="v26-orbit"><span>${phases[0][0]}</span></div><div class="v26-phases">${phases.map((p,i)=>`<button data-i="${i}"><span>${p[0]}</span><b>${p[1]}</b></button>`).join('')}</div><div class="v26-caption">Activa las etapas y observa qué cambia.</div>`;qa('.v26-phases button',stage).forEach((btn,i)=>btn.onclick=()=>{qa('.v26-phases button',stage).forEach(x=>x.classList.remove('on'));btn.classList.add('on');q('.v26-orbit span',stage).textContent=phases[i][0];q('.v26-caption',stage).textContent=`${btn.textContent.trim()}: conecta esta etapa con la anterior y la siguiente.`})}
  function socialStage(stage){const stops=[['🏠','Inicio'],['🌳','Comunidad'],['🏛️','Institución'],['🗺️','Territorio']];stage.innerHTML=`<div class="v26-route"><span>🚲</span></div><div class="v26-stops">${stops.map((s,i)=>`<button data-i="${i}"><span>${s[0]}</span><b>${s[1]}</b></button>`).join('')}</div><div class="v26-caption">Toca los lugares para recorrer la historia.</div>`;qa('.v26-stops button',stage).forEach((btn,i)=>btn.onclick=()=>{qa('.v26-stops button',stage).forEach(x=>x.classList.toggle('on',Number(x.dataset.i)<=i));q('.v26-route span',stage).style.left=`${i*29}%`;q('.v26-caption',stage).textContent=`Llegaste a ${btn.textContent.trim()}. ¿Qué cambia aquí?`})}
  function englishStage(stage,prompt){const n=String(prompt).toLowerCase();const objects=/mother|father|sister|brother|family/.test(n)?[['👩','mother'],['👨','father'],['👧','sister'],['👦','brother']]:/red|blue|green|yellow|color/.test(n)?[['🔴','red'],['🔵','blue'],['🟢','green'],['🟡','yellow']]:/hello|hi|morning|night|salud/.test(n)?[['👋','hello'],['🙂','hi'],['🌞','good morning'],['🌙','good night']]:[['🪑','chair'],['📘','book'],['🚪','door'],['🪟','window']];stage.innerHTML=`<div class="v26-room">${objects.map((o,i)=>`<button class="o${i}" data-label="${o[1]}"><span>${o[0]}</span><b>${o[1]}</b></button>`).join('')}</div><div class="v26-character right">🐸 <small>Touch an object</small></div><div class="v26-caption">Toca un objeto para unir imagen + palabra.</div>`;qa('.v26-room button',stage).forEach(btn=>btn.onclick=()=>{qa('.v26-room button',stage).forEach(x=>x.classList.remove('on'));btn.classList.add('on');q('.v26-caption',stage).textContent=`${btn.dataset.label}. Mira la imagen mientras lees la palabra.`})}
  function renderScene(scene,subject,prompt=''){const stage=q('.v26-stage',scene);if(!stage)return;if(subject==='language')languageStage(stage,prompt);else if(subject==='science')scienceStage(stage,prompt);else if(subject==='social')socialStage(stage);else if(subject==='english')englishStage(stage,prompt);else mathStage(stage,prompt);q('.v26-scene-action',scene)?.addEventListener('click',()=>scene.classList.toggle('expanded'))}

  function installHome(){const home=q('#learningHub'),head=q('.home-head',home);if(!home||!head||q('#v26HomeStory',home))return;const el=document.createElement('section');el.id='v26HomeStory';el.className='v26-home';el.innerHTML='<div class="v26-nova">N</div><div><small>HOY CON NOVA</small><strong>Una misión. Una historia. Una idea por descubrir.</strong></div><div class="v26-icons"><span>➗</span><span>📖</span><span>🔬</span><span>🌎</span><span>💬</span></div>';head.insertAdjacentElement('afterend',el);home.classList.add('v26-condensed')}
  function installSubject(){const hub=q('#curriculumSubjectHub'),hero=q('.curriculum-subject-hero',hub);if(!hub||!hero||q('#v26SubjectMotion',hub))return;const el=document.createElement('div');el.id='v26SubjectMotion';el.className='v26-subject-motion';el.setAttribute('aria-hidden','true');el.innerHTML='<span></span><span></span><span></span><b>N</b>';hero.appendChild(el);hub.classList.add('v26-condensed')}
  function syncTopic(){const hub=q('#curriculumTopicHub');if(!visible(hub))return;const title=text('#curriculumTopicTitle',hub),goal=text('#curriculumTopicGoal',hub),subject=activeSubject(hub),sig=`${subject}|${title}|${goal}`;if(!title||sig===topicSignature)return;topicSignature=sig;q('#v26TopicScene',hub)?.remove();const anchor=q('.topic-focus-card',hub);if(!anchor)return;const wrap=document.createElement('div');wrap.id='v26TopicScene';wrap.innerHTML=shell({subject,title,copy:goal,compact:true});anchor.insertAdjacentElement('afterend',wrap);renderScene(q('.v26-scene',wrap),subject,`${title} ${goal}`);hub.classList.add('v26-condensed');track('narrative_scene_viewed',{surface:'topic',subject,title:short(title,80)})}
  function syncGame(){const modal=q('#curriculumGameModal');if(!visible(modal))return;const prompt=text('#curriculumGamePrompt',modal),title=text('#curriculumGameTitle',modal),round=text('#curriculumGameRound',modal),subject=activeSubject(modal),sig=`${subject}|${round}|${prompt}`;if(!prompt||sig===gameSignature)return;gameSignature=sig;q('#v26GameScene',modal)?.remove();const anchor=q('#curriculumGamePrompt',modal);if(!anchor)return;const wrap=document.createElement('div');wrap.id='v26GameScene';wrap.innerHTML=shell({subject,title:subject==='math'?'Primero vamos a verlo en movimiento':SUBJECTS[subject].scene,copy:''});anchor.insertAdjacentElement('beforebegin',wrap);renderScene(q('.v26-scene',wrap),subject,prompt);modal.classList.add('v26-game');track('narrative_scene_viewed',{surface:'curriculum_game',subject,round:short(round,60)})}
  function syncAtlas(){const app=q('#app');if(!visible(app)||visible(q('#notebookModule')))return;const title=text('#missionTitle',app),story=text('#storyLine',app)||text('#missionPrompt',app),emoji=text('#animalEmoji',app)||'🦎',sig=`${title}|${story}|${emoji}`;if(!title||sig===atlasSignature)return;atlasSignature=sig;q('#v26AtlasScene',app)?.remove();const game=q('#gameArea',app);if(!game)return;const el=document.createElement('section');el.id='v26AtlasScene';el.className='v26-atlas';el.innerHTML=`<div class="v26-atlas-world"><span class="animal">${esc(emoji)}</span><div class="path"></div>${Array.from({length:6},(_,i)=>`<button data-i="${i}">${i%2?'✦':'●'}</button>`).join('')}</div><div><small>LA HISTORIA EN MOVIMIENTO</small><strong>${esc(short(story||title,90))}</strong><span>Toca los puntos para recorrer la misión.</span></div>`;game.insertAdjacentElement('beforebegin',el);qa('.v26-atlas-world button',el).forEach((btn,i)=>btn.onclick=()=>{qa('.v26-atlas-world button',el).forEach(x=>x.classList.toggle('on',Number(x.dataset.i)<=i));q('.animal',el).style.left=`${8+i*13}%`});app.classList.add('v26-condensed');track('narrative_scene_viewed',{surface:'atlas',subject:'math',title:short(title,80)})}
  function syncAcademy(){const view=q('#academyPracticeView');if(!visible(view))return;const title=text('#academyPracticeTitle',view),goal=text('#academyPracticeGoal',view),sig=`${title}|${goal}`;if(!title||sig===academySignature)return;academySignature=sig;q('#v26AcademyScene',view)?.remove();const anchor=q('#academyChallenge',view);if(!anchor)return;const wrap=document.createElement('div');wrap.id='v26AcademyScene';wrap.innerHTML=shell({subject:'math',title,copy:goal,compact:true});anchor.insertAdjacentElement('beforebegin',wrap);renderScene(q('.v26-scene',wrap),'math',`${title} ${goal}`);view.classList.add('v26-condensed');track('narrative_scene_viewed',{surface:'academy',subject:'math',title:short(title,80)})}
  function syncNotebook(){const view=q('#notebookLessonView');if(!visible(view))return;const title=text('#notebookStepTitle',view),cycle=text('#notebookCycleLabel',view),a=text('#notebookDividend',view),b=text('#notebookDivisor',view),sig=`${title}|${cycle}|${a}|${b}`;if(sig===notebookSignature)return;notebookSignature=sig;q('#v26NotebookMotion',view)?.remove();const anchor=q('.division-layout',view)?.parentElement;if(!anchor)return;const el=document.createElement('section');el.id='v26NotebookMotion';el.className='v26-notebook';el.innerHTML=`<div class="eq"><span>${esc(a||'?')}</span><b>÷</b><span>${esc(b||'?')}</span></div><div class="cycle">${['DIVIDO','MULTIPLICO','RESTO','BAJO','REPITO'].map((s,i)=>`<button data-i="${i}"><span>${['➗','✖️','➖','⬇️','🔁'][i]}</span><b>${s}</b></button>`).join('')}</div><p>${esc(short(title||cycle||'Haz un paso a la vez.',90))}</p>`;anchor.insertAdjacentElement('afterend',el);qa('.cycle button',el).forEach(btn=>{btn.classList.toggle('on',cycle.toUpperCase().includes(q('b',btn).textContent));btn.onclick=()=>{qa('.cycle button',el).forEach(x=>x.classList.remove('on'));btn.classList.add('on')}});view.classList.add('v26-condensed');track('narrative_scene_viewed',{surface:'notebook',subject:'math',step:short(title,80)})}
  function installTutor(){const hub=q('#novaTutorHub'),hero=q('.nova-tutor-hero',hub);if(!hub||!hero||q('#v26TutorMotion',hub))return;const el=document.createElement('div');el.id='v26TutorMotion';el.className='v26-tutor';el.setAttribute('aria-hidden','true');el.innerHTML='<span>N</span><i></i><i></i><i></i>';hero.appendChild(el);const chat=q('#novaGeneralChat',hub);if(chat)new MutationObserver(()=>{el.classList.remove('think');void el.offsetWidth;el.classList.add('think')}).observe(chat,{childList:true,subtree:true})}
  function sync(){installHome();installSubject();installTutor();syncTopic();syncGame();syncAtlas();syncAcademy();syncNotebook();document.body.classList.add('nova-v26')}
  function init(){document.documentElement.dataset.novaVisualVersion=VERSION;sync();new MutationObserver(()=>requestAnimationFrame(sync)).observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['hidden','class']});window.addEventListener('nova:v25:updated',sync);track('visual_narrative_enabled',{version:VERSION});window.NOVAVisualNarrative={version:VERSION,sync,subjects:Object.keys(SUBJECTS)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0),{once:true});else setTimeout(init,0);
})();
